eureka:
  client:
    service-url:
      defaultZone: http://localhost:18888/eureka #本地开发
#      defaultZone: http://202.196.37.147:18888/eureka #服务器环境
management:
  security:
    enabled: false
server:
  port: 5000
spring:
  application:
    name: server-admin
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream,activiti