server:
  port: 8848
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: zutnlp-platform-admin
  boot:
    admin:
      client:
        url: http://localhost:5000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zutnlp
    password: zutnlp_123
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/zutnlp_cs_admin?useUnicode=true&characterEncoding=utf8 #本地开发
    url: jdbc:mysql://202.196.37.146:3306/zutnlp_cs_admin?useUnicode=true&characterEncoding=utf8 #服务器开发
#eureka:
#  instance:
#    hostname: ${spring.application.name}
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://202.196.37.169:18888/eureka/ #服务器环境
#      defaultZone: http://127.0.0.1:18888/eureka/ #本地开发
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"