server:
  port: 18888
spring:
  application:
    name: center
  security:
    user:
      name: root
      password: 123456
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://root:123456@localhost:18888/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost